#config.yml使用的是GBK编码，如果你的系统只支持utf-8，请把本文档编码转为utf-8
#词条
?领地: '输入/res'
?查水表: '请输入/co i'
?回到主城: '请输入/spawn'
#增加词库的地方，增加时请在空白地方写上?XXX： ‘XXXX’
#?XXX: "xxx" 记住第一格为?，在：后空一个再输入"内容"
#前缀名字，例如你的name为xxx，当触发时会看到<xxx>:xxxx
#格式为'<xxx>:'
name:  '<百科娘>：'
#当提问的词条在config里不存在时，就会发送nothing的消息
nothing: '抱歉，《百科》里没有这个内容'
#改变颜色的方法，在’‘里，信息前添加§颜色符，颜色符网址http://wiki.ess3.net/mc/
#例如你想改变name的颜色，就§9<百科娘>:就会变成蓝色。改nothing里的内容，
#格式为"§9抱歉，《百科》百科里没有这个内容，就会变成蓝色。
#改词条的内容，例如?领地: '输入/res'的'输入/res'改为蓝色，就'§9输入/res'
#切记，?领地等这些问题不可以改变颜色的！！
